### ISSUE TITLE
[Doc]需要提供贡献指南

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/wuhan2020#1]
需要提供简要的贡献指南，如 csv 文件编辑格式、本地编辑预览、GitHub 操作流程等。

**Comment by sunshinemingo** [comment]
我先来做这个吧

**Comment by frank-zsy** [comment]
这个文档用 Markdown 格式来写，主要包含如下几个主要信息：
* GitHub 操作流程，可参考 X-lab 流程信息，主要包含 fork、clone、branch、PR 流程等
* 提供项目机器人说明，主要包含 /self-assign 领取任务和 /approve 进行 PR review 与自动合入流程

**Comment by frank-zsy** [comment]
另外需要提供 csv 文件的编辑指南，例如：
* 使用半角 `,` 分割
* 如果数组，也用 `,` 分割
* 如果内容中包含 `,` ，例如数组内容，则使用半角 `"` 进行包裹
* 如果使用 VSCode 进行编辑，可以使用 `Edit csv` 插件进行本地测试

**Comment by sunshinemingo** [comment]
收到

**Comment by tonychenxyz** [comment]
觉得这个项目真的很好！刚在朋友圈和几个计算机相关的微信大群里做了转发！

**Comment by frank-zsy** [comment]
谢谢支持，也希望有消息的朋友贡献消息来源 @tonychenxyz

**Comment by sodabear** [comment]
> * X-lab 流程信息

 哪里可以看到 X-lab 流程信息？

**Comment by heming6666** [comment]
> > * X-lab 流程信息
> 
> 哪里可以看到 X-lab 流程信息？

@sunshinemingo 已将其体现在该 [PR](https://github.com/wuhan2020/wuhan2020/pull/10) 当中。

**Comment by frank-zsy** [comment]
fixed by #10
