### ISSUE TITLE
[news]是否需要增加一个疫情数据相关信息的模块呢？

### ISSUE THREAD

**Issue by shadowings-zy** [wuhan2020/wuhan2020#103]
您好，我在贡献指南中看到了本项目也会包含“疫情新闻动态相关信息”的内容。
所以我想和大家探讨一下本项目可不可以再开一个模块去收集每日的疫情数据的信息呢？

我这边已经有整理好的从1月21日-1月26日的每日疫情数据，数据来源是
国家卫生健康委员会（这个是官方数据，最为准确）：http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

和丁香园实时数据（参考此github项目，但丁香园的数据只能作为一个参考）：https://github.com/BlankerL/DXY-2019-nCoV-Crawler

如果有需要的话，我可以将这部分数据贡献到石墨文档中，并按天持续更新。

PS：另外，我是一名前端开发者，如果本项目的前端有什么新feature的话，也可以一起合作哈。

**Comment by nwljy** [comment]
数据来源 网易  
http://news.163.com/special/epidemic/?spssid=7dc3ace025c1193fdf6a842ea671d83d&spsw=1&spss=other#map_block  
获取xpath地址：  
省：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//div[@Class='province']  
市：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//ul//li  
已经用java验证过了

**Comment by nwljy** [comment]
java版本已经写出来

> 数据来源 网易
> http://news.163.com/special/epidemic/?spssid=7dc3ace025c1193fdf6a842ea671d83d&spsw=1&spss=other#map_block
> 获取xpath地址：
> 省：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//div[@Class='province']
> 市：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//ul//li
> 已经用java验证过了

**Comment by nwljy** [comment]
@shadowings-zy 大家共勉，qq 605214875

**Comment by will-ww** [comment]
你们很棒~ @shadowings-zy @nwljy

**Comment by nwljy** [comment]
国家卫生健康委员会（这个是官方数据，最为准确）：http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml 这个搞掂

**Comment by shadowings-zy** [comment]
> java版本已经写出来
> 
> > 数据来源 网易
> > http://news.163.com/special/epidemic/?spssid=7dc3ace025c1193fdf6a842ea671d83d&spsw=1&spss=other#map_block
> > 获取xpath地址：
> > 省：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//div[@Class='province']
> > 市：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@Class='hasCities']//ul//li
> > 已经用java验证过了

嗯嗯这个我也看过，和丁香园的数据是一致的。
但是我比较好奇的是，他们是怎么拿到各省市的详细数据的？
国家健康委员会给出的官方数据中是不包含省市详细信息的，所以针对这部分数据（不论是丁香园还是网易）我一直有点担心是否准确。

PS：网易的页面我看了一下源代码，数据存在了是window.data_from_qq变量中，看起来是腾讯提供的数据。

另外如果需要这部分数据的话，我一直没在石墨文档中找到相关的模块ORZ，没办法将数据共享出来啊

**Comment by shadowings-zy** [comment]
> 国家卫生健康委员会（这个是官方数据，最为准确）：http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml 这个搞掂

这里的数据我都已经处理好了，现在就差在哪里共享这部分数据了

**Comment by frank-zsy** [comment]
赞，如果想在项目中添加的话，可以直接提 Issue 到前端项目，看前端项目有没有人可以接入到网页 @shadowings-zy ，石墨只是临时录入，我们最终目标都是线上展示、检索，已有结构化数据的不需要落入石墨中

**Comment by nwljy** [comment]
后端spring boot 程序我昨天通宵弄完了 ，看看几时需要传上去github

**Comment by nwljy** [comment]
腾讯云的服务器10元一个月找个学生就弄到，不贵

**Comment by shadowings-zy** [comment]
> 腾讯云的服务器10元一个月找个学生就弄到，不贵

兄弟先别着急~
服务器资源我这里就有哈，阿里云ECS。
前端页面我这边也弄好了，我现在在看此项目的前端代码，看看能否合到一起（不过看起来有点困难，毕竟项目前端用的技术栈有点小众）。

**Comment by nwljy** [comment]
> > 腾讯云的服务器10元一个月找个学生就弄到，不贵
> 
> 兄弟先别着急~
> 服务器资源我这里就有哈，阿里云ECS。
> 前端页面我这边也弄好了，我现在在看此项目的前端代码，看看能否合到一起（不过看起来有点困难，毕竟项目前端用的技术栈有点小众）。

靠，我腾讯云11.11都买了1年

**Comment by nwljy** [comment]
毕竟搞后端加上运维，没服务器在手测试不了工作困难

**Comment by exfly** [comment]
找到了这个 https://www.zjwjw.gov.cn/art/2020/1/27/art_1202101_41857304.html
看起来一些省份 卫生健康委员会 会公布各市的数字

**Comment by shadowings-zy** [comment]
嗯，我研究了一下目前已有的疫情数据统计的页面，找到了腾讯疫情数据的接口：
https://view.inews.qq.com/g2/getOnsInfo?name=wuwei_ww_area_counts

直接请求就能得到疫情数据，可以直接拿来用。
另外网易的实时疫情数据页面是直接请求的腾讯的接口……也是醉了。

**Comment by nwljy** [comment]
那就蛋疼。。我直接抓了数据。

**Comment by nwljy** [comment]
你是怎样找到的？方法？

**Comment by shadowings-zy** [comment]
> 那就蛋疼。。我直接抓了数据。



> 你是怎样找到的？方法？

https://news.qq.com/zt2020/page/feiyan.htm
打开这个页面后F12查看网页源代码，我读了一下源代码就找到了。

**Comment by tongshuangwu** [comment]
@shadowings-zy 小伙伴现在整理好的信息是每日每个市级的新增？我们有一个前端的分组在做map visualization，想按时序和地理位置跟踪疫情变化的。如果你在slack群的话可以来 #map-visualization 这个channel我们聊一下数据的问题呀~

**Comment by shadowings-zy** [comment]
好的

**Comment by nwljy** [comment]
几位大哥拉我一下

**Comment by tongshuangwu** [comment]
在那个channel里艾特你了~
再楼上的那位大佬没找到id是啥= =
其实点slack左边那个Channels就可以看到+加入到任何一个channel里。

**Comment by shadowings-zy** [comment]
> 在那个channel里艾特你了~
> 再楼上的那位大佬没找到id是啥= =
> 其实点slack左边那个Channels就可以看到+加入到任何一个channel里。

我已经在频道中了哈，我的id是shadowingszy

**Comment by alfredcs** [comment]
有哪位大神贡献一下历史数据？这个URL只有当天的，希望能够得尽量多的数据点。多谢！https://view.inews.qq.com/g2/getOnsInfo?name=wuwei_ww_area_counts
