### ISSUE TITLE
[new]可否添加在线诊断功能

### ISSUE THREAD

**Issue by DecimaViktor** [wuhan2020/wuhan2020#108]
用选择的方式选择症状，然后给予建议

**Comment by HiiHongFe** [comment]
这个项目主要是信息收集，在线诊断其实阿里和腾讯都有在做

**Comment by DecimaViktor** [comment]
那加个跳转链接到阿里或者腾讯那里？

**Comment by xwr96** [comment]
我觉得在线诊断可以添加百度的问医生，昨天开始推出的

**Comment by yinzhangyue** [comment]
网站中已添加，https://wh.opensource-service.cn/#/free_consultation
