### ISSUE TITLE
wuhan.support

### ISSUE THREAD

**Issue by yc-zc** [wuhan2020/wuhan2020#11]
您好，我是 wuhan.support 项目的维护人

目前，我们正和 Polaris 的团队合作，一起搭建武汉肺炎疫情信息的数据库

如您愿意，希望我们能一起合作，避免重复建设

**Comment by frank-zsy** [comment]
好的，我们关注一下，也欢迎共建本项目

**Comment by will-ww** [comment]
> 您好，我是 wuhan.support 项目的维护人
> 
> 目前，我们正和 Polaris 的团队合作，一起搭建武汉肺炎疫情信息的数据库
> 
> 如您愿意，希望我们能一起合作，避免重复建设

欢迎分享你们的项目信息，一起合作，众志成城！

**Comment by NeverMin** [comment]
建议合并到 wuhan.support

**Comment by momodezhou** [comment]
看到目前信息都是网上（自媒体或者官网报道），一些捐赠援助信息是朋友圈流传，无法确定真实性。

**Comment by frank-zsy** [comment]
@NeverMin 由于目前合作方较多，参与同学也较多，我们暂时无法合并到其他项目，也请继续关注我们的项目。
