### ISSUE TITLE
点击邮寄地址出现问题

### ISSUE THREAD

**Issue by xiaohuiduan** [wuhan2020/wuhan2020#110]
在我点击邮寄地址后出现以下提示(用不同浏览器)
1. Write permission denied(via 浏览器)
2. 已复制到剪贴板(夸克)
3.没有任何提示(小米浏览器，和via)

**Comment by frank-zsy** [comment]
前端问题，请提 Issue 到前端项目：https://github.com/wuhan2020/wuhan2020.github.io/issues/new
