### ISSUE TITLE
[News]武汉火神山医院紧急招募 IT 运维志愿者需求!

### ISSUE THREAD

**Issue by qianlinjun** [wuhan2020/wuhan2020#124]
转自https://mp.weixin.qq.com/s/6cjgkHcbAQBPiCuKmBjYCw
**以企业为单位组织报名，不接受个人报名**

为抗击新型冠状病毒感染的肺炎疫情，确保建设中的火神山医院信息系统正常运转，现面向全国 IT 企业公开招募院内 IT 运维志愿者。

委托 HIT 专家网发布具体需求如下：

一、工作地点：火神山医院（武汉市蔡甸区）。
二、工作内容：院内（含污染区）终端维护，包括电脑、打印机、终端网络等桌面运维工作。
三、报名条件：熟悉医院 IT 业务和桌面运维工作内容，勇于担当奉献的 IT 企业组织的志愿者队伍。公司地域不限，志愿者须驻场承担终端运维工作。

四、工作周期：预计到疫情结束为止。
五、工作期间，医院将提供相关防护措施。
六、对于志愿者交通食宿方面的需求，医院信息筹备组将尽可能予以协调帮助。
七、具体将根据志愿者人员数量，决定排班计划，每次进入污染区 2-4 小时。
**八、报名联系人：HIT 专家网 朱小兵 （微信号：zhu_HIT，电话：19910639570）**

火神山医院信息筹备组
2020 年 1 月 26 日

附件：IT 企业志愿者报名表
企业名称：
擅长专业：
联系人姓名：     
联系人电话：
预计组织志愿者人数：
（请**以企业为单位组织报名，不接受个人报名**）

以上信息可靠，来源：HIT 专家网丨火神山医院信息筹备组
众志成城，驰援武汉！

**Comment by inkydragon** [comment]
上微信搜一搜，已经结束了。

**Comment by qianlinjun** [comment]
是的，已经结束了，谢谢提醒！
