### ISSUE TITLE
[Feature]数据爬虫抓取实时信息

### ISSUE THREAD

**Issue by sodabear** [wuhan2020/wuhan2020#13]
实现数据爬虫，从主要媒体渠道爬取实时信息，以 Issue 形式提交到该项目。

**Comment by ilovefuju** [comment]
这个现在有人在做吗？需要帮忙吗？
我是后端/算法程序员，想看看有没有什么能帮忙做的。

**Comment by frank-zsy** [comment]
@ilovefuju 这个 Issue 和 #6 重复了，我先关闭，可以移步那个 Issue，目前有部分接口可以获取实时新闻数据，可以写一个脚本来做这个事情，我这边也会提供一个框架，后续可以集成到框架中，我计划用 TypeScript 编写框架。
