### ISSUE TITLE
 [Feature]添加项目的后端服务器

### ISSUE THREAD

**Issue by LiuChangFreeman** [wuhan2020/wuhan2020#17]
前端项目地址:
https://github.com/wuhan2020/front-pages
现需要搭建一个代理服务器，需实现以下功能:
1. 使用crontab定期缓存本项目的csv文件信息，保存到服务器本地
2. 提供http接口供前端获取数据，格式为json

后端项目地址:
https://github.com/wuhan2020/api-server

**Comment by frank-zsy** [comment]
提一个建议，前端展示和 API Server 是数据的直接使用方，你们在开发过程中需要随时发现问题，并随时修改数据格式，对原始数据（csv）格式修改的需求请以 Issue 形式提入该项目

**Comment by LiuChangFreeman** [comment]
我提议使用python-flask框架
1. 开发速度快，环境搭建简单
2. 人手较多
3. 比较适合本项目使用

同时建议将flask部署到阿里云serverless函数计算上
1. 支持自动伸缩和并发
2. 不用考虑服务器托管问题
3. 自动化部署很简单

**Comment by spemed** [comment]
我有腾讯云服务器一台可以借出去,仍有需要请call我一下,服务器上现有php+nginx环境。

**Comment by frank-zsy** [comment]
后端项目讨论可移步 https://github.com/wuhan2020/api-server 项目
