### ISSUE TITLE
[Hospital]添加首批医院信息

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/wuhan2020#2]
添加首批医院信息，参考链接：
* https://mp.weixin.qq.com/s/Hq5lo9fbGH5mTON15eDsCw
* https://shimo.im/docs/cRrJwHdGXdX9CP8x/read

录入信息时请务必核实信息有效性，提供有效官方链接或官方媒体发布链接

**Comment by JerryKuan** [comment]
我可以先来帮忙整理这个

**Comment by JerryKuan** [comment]
有些医院我在官网和微信公众号都没有找到接受捐赠公告，是类似澎湃新闻、头条新闻等第三方媒体发布，并且声称已经向该医院求证。那捐赠的官方链接是否可以放第三方新闻报道链接（会备注来源）？

**Comment by frank-zsy** [comment]
我觉得是可以使用比较大流量的媒体报告链接作为来源链接

**Comment by JerryKuan** [comment]
我用了人民日报微博报道作为引用来源

**Comment by frank-zsy** [comment]
> 我用了人民日报微博报道作为引用来源

可以的，那没有问题的

**Comment by liwen-tj** [comment]
关于医院信息，不知道我们能不能具体到每家医院每种物资大概需要多少

目前看到的只是说需要物资，没有具体的数目

**Comment by sodabear** [comment]
所需要的物资信息建议拆散

**Comment by frank-zsy** [comment]
> 所需要的物资信息建议拆散

可以讨论一下，目前使用 csv 文件主要是为了前端方便获取和解析，如果数组类信息约定通过`,` 或 `、`分割，则前端可以直接做信息拆解工作，目前其实是要求一律用 `,` 分割的，之后可以进一步修改一下文件内容。

**Comment by sodabear** [comment]
将 | 所需物资信息 这一列 细分为
----------------
所需N95口罩数量 | 所需防护眼镜数量 | 所需防护帽数量 | 所属手术衣数量 | 所需医用一次性乳胶手套数量 | 所需手术衣数量 | 所需物资信息

是否合理

**Comment by frank-zsy** [comment]
> 是否合理

目前主要问题是，我们没有发现有消息源可以获取每种物资的具体所需数量，医院并未公布所需数量信息，如果要如此拆分，则需要有专门的同学进行一一的电话联系和确认，这个成本可能较高

**Comment by frank-zsy** [comment]
fixed by #8
