### ISSUE TITLE
希望添加感染车次航班等信息--已有持续更新数据提供

### ISSUE THREAD

**Issue by dlunion** [wuhan2020/wuhan2020#204]
今天我根据人民日报手动把信息录入到系统，并放入我的[wuhan项目](https://github.com/dlunion/wuhan)中，您可以访问并下载数据。同时为了便于快速查询，我也开发了一个[查询系统](http://zifuture.com:1000/)，数据会持续更新。希望能为大家提供帮助，尽快查找异常感染人群。

**Comment by frank-zsy** [comment]
请问之前的数据有吗？之后还会继续维护吗？

**Comment by dlunion** [comment]
> 请问之前的数据有吗？之后还会继续维护吗？

请查看[wuhan项目](https://github.com/dlunion/wuhan)里面的数据，之后会持续维护，紧跟官方发布消息

**Comment by zmingchun** [comment]
人民日报联合无糖提供了 查询工具：[新型冠状病毒感染的肺炎
确诊患者同行程查询工具]
[新型冠状病毒感染的肺炎
确诊患者同行程查询工具]:https://h5.peopleapp.com/txcx/index.html

**Comment by tongshuangwu** [comment]
楼上的数据：http://2019ncov.nosugartech.com/data.json

**Comment by dlunion** [comment]
官方已经提供工具，谢谢。我在这里退出啦。。谢谢
