### ISSUE TITLE
深度学习助力

### ISSUE THREAD

**Issue by GlassyWing** [wuhan2020/wuhan2020#216]
以下为使用RNN进行微分方程拟合出的结果，累计确诊人数估计在2月8号左右将到达峰值，最终确诊人数在12000±2000左右，以下结果仅根据29号前的数据进行估计，并仅此作为参考，![ncov](https://user-images.githubusercontent.com/17000429/73417723-152ff600-4354-11ea-8a33-6faca418445b.png)

**Comment by JinXJinX** [comment]
1月30号的数据是7750+吧。很贴近哎

**Comment by owenhust** [comment]
这个是实际确诊 还是实际感染？

**Comment by GlassyWing** [comment]
> 这个是实际确诊 还是实际感染？

实际确诊

**Comment by owenhust** [comment]
谢谢，这是个不错的baseline，不过对于实际传染或许更有价值，只是数据还需要搜集。

**Comment by shengyang998** [comment]
考虑返程高峰没有？

**Comment by renyuzhuo** [comment]
这种信息可以供研究学习使用，非权威机构不建议公开传播这种数据。

[**提交自 GitHub Hot 小程序**](https://github.com/renyuzhuo/GitHub-Hot)

**Comment by GlassyWing** [comment]
由于可能产生的误导作用，关闭这个问题

> 这种信息可以供研究学习使用，非权威机构不建议公开传播这种数据。
> 
> [**提交自 GitHub Hot 小程序**](https://github.com/renyuzhuo/GitHub-Hot)

的确，鉴于可能产生的误导作用，还是关闭此问题

**Comment by zhangyixin1222** [comment]
疫情存在太多不确定性，这类数据应该推送给权威机构和相关决策机构作为做出决策时候也的考虑因素，而不建议作为公开场合作为指导方案
