### ISSUE TITLE
医院的物资数量未知时页面显示个数为1

### ISSUE THREAD

**Issue by Neway6655** [wuhan2020/wuhan2020#230]
建议做个友好的前端展示，对于“数量未知”的物资需求，我们是否要展示/如何展示？

另外，我们这个平台已经对外推广出去了吗？目前了解到一些武汉医院又开始新一轮物资缺乏了。

**Comment by Caagei** [comment]
> [https://user-images.githubusercontent.com/34957140/73586578-48a48900-44ea-11ea-8899-3bbf69abcb34.png](url)

**Comment by Caagei** [comment]
#261 的相关截图 https://user-images.githubusercontent.com/34957140/73586578-48a48900-44ea-11ea-8899-3bbf69abcb34.png

**Comment by Caagei** [comment]
已有Pr https://github.com/wuhan2020/WebApp/pull/41
