### ISSUE TITLE
是否考虑增添推荐就诊模块

### ISSUE THREAD

**Issue by wang-sy** [wuhan2020/wuhan2020#244]
根据患者（准）的定位，向患者推荐就近的医院，并且可以直接切换到 ( 高德导航 \ 百度地图 等 ) 进行导航，方便患者就诊

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
除非我们能接入对应医院的数据库,
否则, 比不过当地人民自己的熟悉程度,
而且, 对医院资源的预测没有任何依据, 只根据地理位置来推荐,
不如现有地图 app 的推荐呢.

如果我们代表医院进行推荐, 可能加重已经资源不足的知名医院的服务混乱.

**Comment by Caagei** [comment]
目前我们尚未有途径获取医院医疗资源余量的数据，难以达到“推荐”的效果，如果有这方面的资源，请分享一下。
这个建议我们已经记录下来，感谢建议！
