### ISSUE TITLE
Iphone 打开web 首页没问题，点开里面的任何一页都是无限转圈

### ISSUE THREAD

**Issue by xiaojiaqi** [wuhan2020/wuhan2020#247]
Iphone 打开web 首页没问题，点开里面的任何一页都是无限转圈。

浏览器: chrome  safari
Ios: 12.x

**Comment by yinzhangyue** [comment]
是访问http://wuhan2020.org.cn/吗，应该修复了，可以重新尝试一下（测试平台：ios13.3，浏览器Safari）
