### ISSUE TITLE
医院急需物资页面数量显示有问题

### ISSUE THREAD

**Issue by victor23d** [wuhan2020/wuhan2020#261]
![chrome_RxBbnOBkc3](https://user-images.githubusercontent.com/34957140/73586578-48a48900-44ea-11ea-8899-3bbf69abcb34.png)
有很多口罩，防护服数量显示需要1个，这可能没有什么意义。
也有 9.长筒胶鞋/防污染靴 0个
这是不是bug？

**Comment by Caagei** [comment]
#230
