### ISSUE TITLE
Slack加入链接已经失效

### ISSUE THREAD

**Issue by dzy-monkey** [wuhan2020/wuhan2020#263]
# 我会通过别的方式为这个项目做贡献，中国加油

**Comment by GindaChen** [comment]
[https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc](https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc)

**Comment by GindaChen** [comment]
这个链接应该是OK的

**Comment by dzy-monkey** [comment]
> 这个链接应该是OK的
我刚刚尝试了一下，这个链接依然是失效的

**Comment by GindaChen** [comment]
Hi @dzy-monkey 你可以具体描述一下吗？

**Comment by dzy-monkey** [comment]
> 这个链接应该是OK的

非常感谢

**Comment by GindaChen** [comment]
> > 这个链接应该是OK的
> 
> 非常感谢

OK了是吗？

**Comment by dzy-monkey** [comment]
> 嗨@ dzy-monkey你可以具体描述一下吗？比方说是链接直接显示invalid还是有其他的问题
是的，我已经加入了
