### ISSUE TITLE
【提案】将README.md的主要文档合并到wuhan2020.github.io

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020#267]
建议：
1、将README.md的主要文档合并到wuhan2020.github.io
2、留下一些重要的路标类的文档

这样做：
1、方便翻译，目前wuhan2020.github.io 也有一份文档。合并后只维护一份
2、wuhan2020/wuhan2020 项目专职做数据存储和 新人流量入口（目前对外宣传的是https://github.com/wuhan2020/wuhan2020）

**Comment by GindaChen** [comment]
附议。特别建议需要有一个专门的Section或者一个专门的Tab分流新手志愿者

**Comment by JoeZijunZhou** [comment]
@lovepoem 目前大部分文档都在wuhan2020，同时根据总架构图，wuhan2020是数据主仓。我认为应该把翻译组产出所有内容，加入wuhan2020下子文件夹。wuhan2020.github.io应该成为项目官网web端，不存储任何数据。以后如有必要，可以让翻译文本加入json格式等，便于客户端消费。

@GindaChen 目前已在wuhan2020 readme加入 wuhan2020.github.io 导流badge，如有更好的办法可以提出来。

我觉可以在wuhan2020.github.io加入菜单，提供`新手导流`,`多语种新闻消息`（导入翻译组产出内容）等等，成为wuhan2020正式的宣传官网web端，然后https://wuhan2020.kaiyuanshe.cn/ 是wuhan2020应用web端。@lovepoem 你觉得怎么样？

**Comment by GindaChen** [comment]
关于新手导流：建议将**快速开始**变成**我可以做什么？**之类的文字提供新手导流。文档可以直接归类在文档分类下面(`<language>/docs`)

多语种新闻消息：这个可以有，可以和翻译组协商一下

@lovepoem 建议加一个Wuhan2020 WebApp的button。（产品的那个Tab在页面右上角确实不容易被注意到）

**Comment by JoeZijunZhou** [comment]
@GindaChen  wuhan2020.github.io的页面UI优化就交给 @lovepoem 了

**Comment by JoeZijunZhou** [comment]
@GindaChen 这样吧，你可以负责帮忙同步文本到 wuhan2020.github.io。因为目前那是一个doc framework，可能不太方便把数据和服务分离。wuhan2020/wuhan2020下的md就保留在那，方面用户直接阅读

**Comment by lovepoem** [comment]
现在wuhan2020/wuhan2020的文档发我都迁移到 wuhan2020.github.io  。  后期还是维护一份好

**Comment by GindaChen** [comment]
OK 我可能会晚一点catchup这个issue

**Comment by JoeZijunZhou** [comment]
@lovepoem 后期可以维护一份，但目前流量入口还在wuhan2020。另外如果要做整个项目的官网，可能会需要更多功能，这个我不清楚，要看产品，前端他们的做法。只做静态的文档管理，docsite没毛病。感谢你的快速开发！
