### ISSUE TITLE
build: 能否使用submodule的方式将所有代码统一放置在一个仓库

### ISSUE THREAD

**Issue by damingerdai** [wuhan2020/wuhan2020#268]
## 描述
wuhan2020这个项目已经存在很多用于不同的方面的模块。作为一名开发者，如果想参与其中的开发，需要到不同的地方clone代码。请问能不能使用git的submodule或者subtree功能，方便开发者一次性全部下载code。

**Comment by renyuzhuo** [comment]
这个项目中，不同的代码属于不同的功能模块，非从属关系，我认为不应该放到一个仓库中。

[**提交自 GitHub Top 小程序**](https://github.com/renyuzhuo/GitHub-Top)

**Comment by damingerdai** [comment]
放在同一个仓库中并不意味着从属关系，而是方便开发统一clone代码，配置环境。

**Comment by renyuzhuo** [comment]
> 放在同一个仓库中并不意味着从属关系，而是方便开发统一clone代码，配置环境。

我认为：
既然不是从属关系的项目，那有什么理由放到同一个仓库呢，方便开发统一 clone，这是一个伪需求，何况这个项目的协作更多的不是代码方面的，而是数据方面的。
如果真的有大规模 pull 代码的需求，那应该提供脚本、manifest 等方案，而不是 submodule。

**Comment by damingerdai** [comment]
嗯，好，你说的挺有道理的
