### ISSUE TITLE
[bug] CONTRIBUTING文件的Slack邀请地址失效

### ISSUE THREAD

**Issue by bao1018** [wuhan2020/wuhan2020#271]
#pwc
https://github.com/wuhan2020/wuhan2020/blob/master/CONTRIBUTING.md
里面的Slack邀请地址现在失效了，
应该为
https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc

**Comment by haiyuem** [comment]
这个链接现在也失效了，可否再更新一下？

**Comment by chenrui333** [comment]
@bao1018 @haiyuem 我刚加了一个 PR 来更新这个。
