### ISSUE TITLE
最大的问题求解决方法，如果不能求做记录，传递给更多的人。

### ISSUE THREAD

**Issue by loo41** [wuhan2020/wuhan2020#275]
- 各位也是爱国人士，为本次疫情出谋划策，为国难尽心尽力，实属倾佩，我同各位一样，以前充满了民族自豪感，我还在上学，在本次疫情中也捐了一分心，虽然很少，但是在疫情中我慢慢丧失了这一份民族自豪感，所谓前方吃的紧，后面紧着吃，倍感痛心啊，各位爱国人士在这里尽心尽力，但是一些不做为的人紧着吃，红会敷衍了事，实属痛心，网上民愤四起，但终究会过去，这些东西也会被慢慢的遗忘，我希望各位能出谋划策，让这些伤疤永远记录下去，以做查阅。
- 本来不应该在这里提的，但是没有更合适的开源了。
- 希望不要被关闭。

**Comment by loo41** [comment]
底层的人拼命的干，上面的人紧着吃，又有和意义了。哎，痛心。

**Comment by Prurite** [comment]
中国数字时代，端点星，再不济 web.archive.org 和 archive.is 都可以吧
