### ISSUE TITLE
网页版load不出生产和捐赠部分内容 义诊部分是物流信息？

### ISSUE THREAD

**Issue by lbbin1988** [wuhan2020/wuhan2020#283]
网页版https://wuhan2020.kaiyuanshe.cn/# 显示不出生产和捐赠部分的内容
为什么义诊的部分显示的是物流信息呢？
希望能答疑解惑，谢谢

**Comment by Caagei** [comment]
感谢关注！
生产和捐赠部分正在紧张开发中。
义诊部分信息显示有误的问题已经留意到，正在修复 https://github.com/wuhan2020/WebApp/pull/41

**Comment by TechQuery** [comment]
39d3dd0
