### ISSUE TITLE
修改github首页的风格

### ISSUE THREAD

**Issue by Caagei** [wuhan2020/wuhan2020#292]
相关网页： https://wuhan2020.github.io/zh-cn/

需求：统一产品风格：
把主题色蓝色（#1890ff ）改成#ff6440
左上角的logo 改用白色的版本。（只有首页，其他页面的logo 不变）
右测的插画请加入下图
https://wuhan2020.slack.com/files/UT6U364AY/FTGQWLJR4/wuhan2020-illo.eps

认领后请在Slack上联系@Kate Jia

**Comment by iLtc** [comment]
这个 issue 可以关了，主题色、logo、插画都已经修改过了
