### ISSUE TITLE
github被墙实锤了

### ISSUE THREAD

**Issue by Hcreak** [wuhan2020/wuhan2020#293]
![捕获](https://user-images.githubusercontent.com/15710701/73606028-9b606c80-45e0-11ea-89d2-37e7287ec5d7.PNG)

**Comment by WeileiZeng** [comment]
围观

**Comment by William980918** [comment]
岂止是锤了

**Comment by William980918** [comment]
C:\Windows\System32\drivers\etc\host
199.232.5.194 github.global.ssl.fastly.net
52.74.223.119 github.com
13.250.177.223 github.com
13.229.188.59 github.com
13.114.40.48 github.com
140.82.114.3 github.com
192.30.255.112 github.com
140.82.114.4 github.com
140.82.118.3 github.com
192.30.255.113 github.com
140.82.118.4 github.com
140.82.113.3 github.com
192.30.253.113 github.com
140.82.114.4 github.com

**Comment by Hcreak** [comment]
这个节骨眼上了 方教授还在辛勤工作 感动 不愧是国士无双

**Comment by zzadmin** [comment]
亲测，可用
192.30.253.113      github.com
185.199.108.153    github.github.io
151.101.72.133      assets-cdn.github.com
151.101.185.194    github.global.ssl.fastly.net

**Comment by 785916801** [comment]
我广东这边没有吧

**Comment by dzncloud** [comment]
湖南表示前几天还可以访问，今天不行了。

**Comment by zxh19890103** [comment]
dashabi

**Comment by Hcreak** [comment]
> dashabi

嘴真臭 缺教养
