### ISSUE TITLE
弄一个协作的微信群交流吧

### ISSUE THREAD

**Issue by Jinkeycode** [wuhan2020/wuhan2020#302]
可以提供产品设计，数据收集等能力，安卓、iOS的开发资源。项目负责人进群一起讨论吧
![image](https://user-images.githubusercontent.com/12148377/73638664-cf519580-46a5-11ea-8cec-67ae9fa784b4.png)

**Comment by zhuangbiaowei** [comment]
本项目，有一个slack在顺畅的交流，本issue关闭。

**Comment by Jinkeycode** [comment]
没有用Slack
