### ISSUE TITLE
README_JP translation improvements

### ISSUE THREAD

**Issue by RRFHOUDEN** [wuhan2020/wuhan2020#312]
I would like to correct unnatural expressions in Japanese.
Should I send a pull request when completed?

**Comment by RRFHOUDEN** [comment]
I have completed and sent pull request!

**Comment by chenrui333** [comment]
Thanks for the input, I will need to have someone review and approve the PR before the merge!

**Comment by chenrui333** [comment]
Close the issue as the PR has been merged.
