### ISSUE TITLE
wuhan2020.org.cn页面没有使用https协议

### ISSUE THREAD

**Issue by CharlotteFallices** [wuhan2020/wuhan2020#318]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
## 期待的正确输出
(略)

**Comment by chenrui333** [comment]
@CharlotteFallices 跟现在的部署有关系，谢谢你的 bug report.
