### ISSUE TITLE
[提案] 将Wuhan2020社区网站作为金矿旁边的供水者（在社区官网帮各家“抗疫应用” 做宣传导流）

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020#324]
庚子年初，新型冠状病毒降临中华，使我亿万人民陷于恐慌中。疫区更是有不少人染病或者失去亲人，处于崩溃边缘。政府快速展开行动，“国师”钟南山亲赴疫区。国人个个捐款出力，也展开了自救的序幕。
   幸有**X-LAB和开源社**等国内开源机构发起了**wuhan2020开源社区**。同时孵化出了**新型冠状病毒防疫信息平台项目**。通过建立信息系统的方式，方便资源提供者(医疗资源捐献者、物流公司、酒店、义诊资源)和需要帮助者（医院、灾区群众）之间信息互通，以方便快速地使灾区人民得到救助。
目前Wuhan2020社区有来自**不同国家的3000多志愿者**组成。有程序员、产品经理、设计师、项目经理、数据分析师、信息采集者、翻译、媒体工作者、学生等。通过建立信息系统、进行数据分析预测等为抵抗新型冠状病毒做贡献。
目前社区的流量和关注度也越来越大，我想我们聚在一起正是为了一个愿景：众志成城，驱除瘟疫！同时我们也看到，国内不少同仁们，有国家队，也有地方武装。都开发一个又一个的抗疫病平台，有疫情地图，有抗灾物资服务沟通网站，有数据分析。
       既然我们有这么大的关注和流量，我们社区何不做金矿边的"供水者"。用自己的优势“曲线救国”。
       我提案在社区网站加一个：**抗灾应用导航频道**。收录所有的抗疫病平台: 疫情地图，有抗灾物资服务沟通网站等，按照类目排序，方便大家快速找到自己关注的数据，看到国家和每个个人的努力。使用我们社区的影响力来帮助更多的好的app，同时也提高我们社区的影响力！

**Comment by thinkinnight** [comment]
投一票，我觉得这个功能挺好的，把真正好用的APP通过我们的渠道送达到需要的人。

**Comment by will-ww** [comment]
强烈支持，这个太棒了！

**Comment by XIAMAI2020** [comment]
practical&useroriented👍👍👍

**Comment by frank-zsy** [comment]
强烈支持！应该做的！还有很多官方的重要页面、渠道都应该列出来！

**Comment by thinkinnight** [comment]
* [人民日报全媒体行动，征集新型冠状病毒肺炎求助者信息](https://activity.peopleapp.com/qiuzhutongdao/)

**Comment by William980918** [comment]
赞同并支持很好的想法👍

**Comment by Atena1118** [comment]
支持！！ 我们作为一个其他APP的聚合平台，把国家、团体与个人的努力的成果汇集起来！

**Comment by keeStep** [comment]
http://nav.werty.cn/

**Comment by Atena1118** [comment]
【 2019-nCoV 疫情信息【导航】】
这是一个信息聚合的平台，链接👇：
http://nav.werty.cn

**Comment by Atena1118** [comment]
> 强烈支持！应该做的！还有很多官方的重要页面、渠道都应该列出来！

【 2019-nCoV 疫情信息【导航】】
这是一个信息聚合的平台，链接👇：
http://nav.werty.cn 
赵老师，这个好像也是咱们 哪个志愿者（小团队） 做的，好几天前看到的，

**Comment by lovepoem** [comment]
> http://nav.werty.cn/

看来确实有类似的了

**Comment by thinkinnight** [comment]
https://github.com/KikiLetGo/VirusBroadcast

VirusBroadcast
一个基于java的模拟仿真程序，由于启动的时候时间仓促，数据不足，所以模型和推演过程过于简单，如果有好的想法或者能提供相关数据支持的朋友请提issues。 如果您也是一名java程序员，可以直接修改并给我提交pr，我之前已经启动每日疫情数据的每日抓取工作，希望在疫情结束后有机会通过这些精准的的数据做一个复盘。

**Comment by will-ww** [comment]
> > 强烈支持！应该做的！还有很多官方的重要页面、渠道都应该列出来！
> 
> 【 2019-nCoV 疫情信息【导航】】
> 这是一个信息聚合的平台，链接👇：
> http://nav.werty.cn
> 赵老师，这个好像也是咱们 哪个志愿者（小团队） 做的，好几天前看到的，

这个项目发起人是不是可以考虑一起合到wuhan2020里面来，号召社区一起来完善和细化，相互一起支持~ @wertycn @frank-zsy

**Comment by WeileiZeng** [comment]
支援武汉开源社区项目导航   
https://weileizeng.github.io/OpenSourceWuhan/

这个平台作为一个连结各个项目的入口，欢迎添加您的项目

**Comment by tanjunchen** [comment]
+1

**Comment by lovepoem** [comment]
> > > 强烈支持！应该做的！还有很多官方的重要页面、渠道都应该列出来！
> > 
> > 
> > 【 2019-nCoV 疫情信息【导航】】
> > 这是一个信息聚合的平台，链接👇：
> > http://nav.werty.cn
> > 赵老师，这个好像也是咱们 哪个志愿者（小团队） 做的，好几天前看到的，
> 
> 这个项目发起人是不是可以考虑一起合到wuhan2020里面来，号召社区一起来完善和细化，相互一起支持~ @wertycn @frank-zsy

来通报一下续集，目前姻缘已经达成：

欢迎疫情信息导航项目 2019-nCoV-Nav 进驻Wuhan2020开源社区孵化！
https://github.com/wuhan2020/wuhan2020/issues/346

**Comment by lovepoem** [comment]
Fixed via https://github.com/wuhan2020/wuhan2020/issues/346
