### ISSUE TITLE
[Feature] 我们需要 csv 格式检查工具

### ISSUE THREAD

**Issue by WuShaoling** [wuhan2020/wuhan2020#33]
GitHub 对 csv 文件预览做了美化处理，前提是 csv 文件格式必须正确，如果不正确，则无法美化处理，如下图所示：

![image](https://user-images.githubusercontent.com/16188599/73123129-61cba800-3fc7-11ea-810b-484067ec36c6.png)

为了使大家更好的阅读 csv 文件，现在建议在 CI 中集成 csv 文件检查，如果检查不通过，则阻止 PR 的合并。

**Comment by hitzhangjie** [comment]
可以简单列下基本的格式检查条目吗？

**Comment by frank-zsy** [comment]
由于数据格式修改为 yaml，不再需要 csv 检查工具
