### ISSUE TITLE
[bug]: 酒店数据：很多酒店数据没有酒店名称 #pwc

### ISSUE THREAD

**Issue by zhengewei** [wuhan2020/wuhan2020#331]
hotel json 数据，从第95条往后开始就没有酒店名称：
![image](https://user-images.githubusercontent.com/25046707/73902615-59317680-48d1-11ea-935b-a3036b904070.png)

这样页面的结果就是：
![image](https://user-images.githubusercontent.com/25046707/73902665-7c5c2600-48d1-11ea-9774-3053fd6ab27b.png)

**Comment by damingerdai** [comment]
看了一下shimo的原始数据，本来就没有名字，因为西安市目前有22个区、县提供集中住宿酒店，具体酒店和入住条件请拨打各区、县电话咨询，建议将西安地区单独列出

**Comment by damingerdai** [comment]
https://shimo.im/sheets/pdHRcXyKqJdqPyGJ/MODOC/

**Comment by frank-zsy** [comment]
我来修正一下， 把各区的内容移到酒店列中，使得显示比较合理

**Comment by frank-zsy** [comment]
已修正
