### ISSUE TITLE
Slack分享链接失效

### ISSUE THREAD

**Issue by coolspring1293** [wuhan2020/wuhan2020#335]
* 链接地址: <https://wuhan2020.slack.com/join/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc>

* 显示内容

```
This invite link is no longer active.

Please check with the person who shared it with you to see if there's a new link available.
```

**Comment by konggeyuan** [comment]
好久没反馈了，请更新链接

**Comment by chenrui333** [comment]
谢谢告知，我们会尽快处理。

**Comment by chenrui333** [comment]
谢谢 bug report, 已经 fix.
