### ISSUE TITLE
[slack] 新加坡数据采集

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020#347]
## 描述信息渠道

By Sylvia on slack, https://wuhan2020.slack.com/archives/CSX1LGEKD/p1581177547317900

> 大家接下来可以关注一下新加坡的数据，感觉有可能要爆发

> MOH有更新 https://www.moh.gov.sg/2019-ncov-wuhan

### 如果有的话，请附图

![image](https://user-images.githubusercontent.com/1580956/74091339-47dc9b80-4a84-11ea-822c-05fcea4b795e.png)

**Comment by YuanJiayi** [comment]
<img width="2560" alt="WeChat0d10538a1dcd03de356cb8c43c054af5" src="https://user-images.githubusercontent.com/42376183/75882836-f1813380-5e5c-11ea-9d13-844b38e86a94.png">
3月4日更新如上
出现了新的感染群Wizlearn Technologies, 位于西海岸附近的Science Park
