### ISSUE TITLE
[slack] 社区如何支持关心疫区的女性

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020#350]
## 描述功能要求

from slack, https://wuhan2020.slack.com/archives/CSS83MZUK/p1581181938004900

> Weilei Zeng  12:12 PM
请问这个是我们的服务范围吗

### 如果有的话，请附图

![image](https://user-images.githubusercontent.com/1580956/74091801-cc7de880-4a89-11ea-81df-801bf1451eae.png)

**Comment by reclusive-neural-network** [comment]
昨晚看到抗疫护士被逼写检讨书的事，里边提到了Stacy的经历，突然想起这个issue的标题，顿时明白了。

建议在首页上显著位置新开一个链接，比如**关注战“疫”女性**，客观说明现在女性的困难（如除了在医院工作就是在宾馆/宿舍隔离，没时间购物，必需品又不在统一采购范围之内，也没多少人在捐物资的时候想到）号召大家（尤其是女性）捐物资的时候也多捐女性卫生用品（应该是现在最容易得到的物资了，不可能消耗量大于平常多少），先解决目前的问题。

微博上有个#看见女性劳动者#，建议去蹭曾热度。但是小心这样的话题容易跟快变成平权问题，那就大了。所以建议只关注具体问题。

可以考虑跟韩红基金会合作。

还有[这里](https://baijiahao.baidu.com/s?id=1658378167409997240&wfr=spider&for=pc)提到的微光车队，可能愿意承担运输任务。
