### ISSUE TITLE
汇总/更新 slack 信息

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020#351]
relates to https://github.com/wuhan2020/wuhan2020.github.io/issues/152

**Comment by chenrui333** [comment]
相关石墨文档，https://shimo.im/sheets/6YcV693Y3wqC6qJk/MODOC

**Comment by lovepoem** [comment]
Closed via https://github.com/wuhan2020/wuhan2020.github.io/pull/201
