### ISSUE TITLE
/self-assign does not assign myself?

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020#361]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题

/self-assign 不会将任务assign给我

## 期待的正确输出

/self-assign 把任务assign给我

**Comment by GindaChen** [comment]
不对诶好像可以诶 你要试一试self assign这个issue吗？ @ AnnaCICI

**Comment by lovepoem** [comment]
权限问题。应该是在网站项目，有些权限token没有配置

**Comment by chenrui333** [comment]
`/self-assign` should always work regardless.

**Comment by chenrui333** [comment]
I tried to add hypertrons into both master and dev branches of wuhan2020.github.io repo, seems none of them are working. I will check with @frank-zsy later today on this matter.

**Comment by chenrui333** [comment]
The plain function test in wuhan2020-test repo does not quite work either.
https://github.com/wuhan2020/wuhan2020-test/issues/1

**Comment by chenrui333** [comment]
Closing this issue as the wuhan2020.github.io repo is working as expected. 

Feel free to create a new issue if needed.
