### ISSUE TITLE
删除wh.opensource-service.cn中日人民报患者伪求助通道

### ISSUE THREAD

**Issue by hugetiny** [wuhan2020/wuhan2020#363]
## 当前问题
刚开始我还怀疑会不会官方通过这个可以乱抓人，结果搞了半天发现是形象工程。
一个伪接口，任何Form data都不会报错
或浏览器直接请求https://h5.peopleapp.com/de-info/Info/add
返回结果都是
{"result":{"errorCode":"0","errorMsg":"ok"},"data":[]}
还没见哪个框架请求体是空的不报错的

## 期待的正确输出
删了吧，本来就脏。

**Comment by hugetiny** [comment]
一句话简单点说，就是一个伪接口，返回的是静态数据{"result":{"errorCode":"0","errorMsg":"ok"},"data":[]}

**Comment by chenrui333** [comment]
Thanks for the bug report.

**Comment by hugetiny** [comment]
https://wh.opensource-service.cn/ 现在还有日人民报的链接
