### ISSUE TITLE
给大家提供一个匿名论坛讨论区

### ISSUE THREAD

**Issue by NodeBE4** [wuhan2020/wuhan2020#367]
https://be4.herokuapp.com/category/11/

我知道你们已经有slack了，但是论坛讨论能让公众看到讨论的内容，可以帮助媒体或者其他查找资料的人，对信息扩散可能更有帮助。如果你们有这个需要，欢迎到这里的武汉肺炎专题讨论。论坛注册无需真实邮箱，无验证。

另外，版块内的事务由版主全权处理，所以需要有人申请成为版主。

**Comment by chenrui333** [comment]
其实 美国的隐私讨论网站也挺多的 teamblind 国内也有 脉脉，只不过这些服务更偏职场。

**Comment by chenrui333** [comment]
我先把你这个 issue 关掉了哈 发现你也没什么流量 😅
