### ISSUE TITLE
加一个持续集成插件来加快PR的速度

### ISSUE THREAD

**Issue by xiangyu-sun** [wuhan2020/wuhan2020#37]
加一个持续集成来预审PR，加快PR的速度吧。 Travis， bitraise，现阶段就加一个csv验证就足够了。
至少merge的安心。

**Comment by frank-zsy** [comment]
是的，csv 自动化检查是一个刚需，你这边有好的工具脚本吗？是否可以添加一下 CI？

**Comment by xiangyu-sun** [comment]
不太了解CSV这方面（编码GB？），就把它想成一个脚本吧 ，应该有人有经验可以写一个，现在的话可以先搞一个workflow用来标记PR，就看看github 有没有提供基础csv验证 先吧这个Workflow搞起来，然后再攻验证脚本

**Comment by frank-zsy** [comment]
编码都是 utf-8 的，csv 文件就是纯文本文件，这个和测试 CI 一模一样，就是提供一个脚本在 CI 时检查所有 csv 文件是否格式正确、合法。那这块找有经验的同学来做吧。

**Comment by xiangyu-sun** [comment]
应为需要一定权限，才能设置workflow。 可以创建一个试试。然后我来帮你加新配置。
<img width="796" alt="Screen Shot 2020-01-25 at 8 19 03 PM" src="https://user-images.githubusercontent.com/1487212/73124078-6c2e7780-3fb0-11ea-9c09-e447359270fc.png">
<img width="1592" alt="Screen Shot 2020-01-25 at 8 20 36 PM" src="https://user-images.githubusercontent.com/1487212/73124079-6cc70e00-3fb0-11ea-8326-f5e8b1932a16.png">
<img width="457" alt="Screen Shot 2020-01-25 at 8 21 14 PM" src="https://user-images.githubusercontent.com/1487212/73124080-6cc70e00-3fb0-11ea-8d15-915f7ee78132.png">

**Comment by xiangyu-sun** [comment]
做了个PR。可以给我上PR的权限么
