### ISSUE TITLE
live map的统计数据只显示到了2月11号

### ISSUE THREAD

**Issue by Colstuwjx** [wuhan2020/wuhan2020#370]
## 当前问题
如下图所示，首页上的展示疫情确诊数据的时间日期只显示到了2月11日，是否需要更新到最新？
![image](https://user-images.githubusercontent.com/3972545/74495358-a1c0e380-4f12-11ea-8ace-d31c9355e61f.png)

## 期待的正确输出
能够进行每日更新，或者 iframe/爬取 [丁香医生](https://ncov.dxy.cn/ncovh5/view/pneumonia) 的统计数据。

**Comment by Colstuwjx** [comment]
收到邮件提醒说data sync failed，这可能是需要单独跟进的一个issue：

![image](https://user-images.githubusercontent.com/3972545/74495556-198f0e00-4f13-11ea-99eb-56f4cdec69ea.png)

**Comment by chenrui333** [comment]
我来反馈一下这个问题。

**Comment by frank-zsy** [comment]
是缓存导致的，已经进行了刷新，之后会添加自动刷新的能力。
