### ISSUE TITLE
讨论：建议采用MD表格形式展现数据？

### ISSUE THREAD

**Issue by antiwuhanvirus** [wuhan2020/wuhan2020#39]
MD相对于CSV的优势在于链接，图片等格式易于排版(可链接至原文，原图，便于鉴别真伪）

我在维护海外捐赠信息的汇总情况，希望能够提供外链到捐款发起方，这样可以帮助想捐款的人更便利地鉴别捐款的真实性，如果本项目有更好能实现这些功能的方法，愿意整合数据到这里，谢谢！

https://anti-wuhan-virus.github.io/donation-info-overseas/

**Comment by liwen-tj** [comment]
我觉得对于非程序员群体，markdown流行度不高，人们更熟悉和习惯表格

**Comment by frank-zsy** [comment]
MD 格式只适于进行直接渲染，不适于数据格式
