### ISSUE TITLE
日人民报伪链接一直在https://wh.opensource-service.cn没有修复

### ISSUE THREAD

**Issue by hugetiny** [wuhan2020/wuhan2020#392]
这个issue没有修复
https://github.com/wuhan2020/wuhan2020/issues/363

这个PR貌似没什么用，https://wh.opensource-service.cn 还是有日人民报的链接
https://github.com/wuhan2020/COVID-19-Nav/pull/17

**Comment by wertycn** [comment]
https://github.com/wuhan2020/COVID-19-Nav/pull/21

**Comment by wertycn** [comment]
已解决 , 可关闭 @lovepoem

**Comment by Hcreak** [comment]
日人民报 蛤蛤蛤 没毛病

**Comment by lovepoem** [comment]
Closed via https://github.com/wuhan2020/COVID-19-Nav/pull/21
