### ISSUE TITLE
建议更正文档中"武汉Covid-2019"的说法

### ISSUE THREAD

**Issue by LeoJhonSong** [wuhan2020/wuhan2020#396]
目前新冠疾病已经定名**2019冠状病毒病（COVID-19）**, 病毒定名**严重急性呼吸综合征冠状病毒2（SARS-CoV-2）**,  源自🔗[世卫组织技术指南](https://www.who.int/zh/emergencies/diseases/novel-coronavirus-2019/technical-guidance/naming-the-coronavirus-disease-(covid-2019)-and-the-virus-that-causes-it), 但是**武汉新冠病毒**, **Wuhan Covid-19**这样的说法很容易让人认为这是一种类似**武汉病毒**, **Wuhan Virus**这样有歧视色彩的对疾病的称呼, 而不是有关**武汉地区的新冠疫情**的内容.

建议将几个语言版本的文档都改为更严谨的描述方式, 比如:
- 新冠病毒在武汉地区的疫情
- 武汉地区的新冠病毒疫情
- 武汉地区的Covid-2019疫情
- Epidemic Information of New Coronavirus in Wuhan

望采纳

**Comment by pkufubo** [comment]
附议。原用词存在歧视嫌疑，或不利于防疫进行。

**Comment by lovepoem** [comment]
楼上几个能pr.修正一下么？

**Comment by pkufubo** [comment]
好的 我愿意pr参与



pkufubo@pku.edu.cn
 
发件人： Xin Wang
发送时间： 2020-03-12 08:18
收件人： wuhan2020/wuhan2020
抄送： Bo Fu; Comment
主题： Re: [wuhan2020/wuhan2020] 建议更正文档中"武汉Covid-2019"的说法 (#396)
楼上几个能pr.修正一下么？

**Comment by lovepoem** [comment]
还有就是 : https://github.com/wuhan2020/wuhan2020.github.io 是社区网站，里面有更多的文章，欢迎指正

**Comment by pkufubo** [comment]
请问应该推到哪个branch？



pkufubo@pku.edu.cn
 
发件人： Xin Wang
发送时间： 2020-03-12 08:18
收件人： wuhan2020/wuhan2020
抄送： Bo Fu; Comment
主题： Re: [wuhan2020/wuhan2020] 建议更正文档中"武汉Covid-2019"的说法 (#396)
楼上几个能pr.修正一下么？

**Comment by pkufubo** [comment]
抱歉，我看到文档了，您无需回复
----------------------
请问应该推到哪个branch？



pkufubo@pku.edu.cn
 
发件人： Xin Wang
发送时间： 2020-03-12 08:18
收件人： wuhan2020/wuhan2020
抄送： Bo Fu; Comment
主题： Re: [wuhan2020/wuhan2020] 建议更正文档中"武汉Covid-2019"的说法 (#396)
楼上几个能pr.修正一下么？
―

**Comment by pkufubo** [comment]
已经完成修改，请close
