### ISSUE TITLE
[Discussion]是否默认使用石墨表格编辑

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/wuhan2020#42]
csv 是较好的数据格式，对数据处理非常有利，但提交确实较为困难，我们将提供脚本进行石墨表格的定时同步，是否直接使用石墨作为默认编辑工具，然后由脚本进行数据的定时整理与合入？

**Comment by zhoucheney** [comment]
这个的话能直接用excel存么，感觉数据量并不大

**Comment by hitzhangjie** [comment]
@zhoucheney 感觉这个方法可以

**Comment by frank-zsy** [comment]
> 这个的话能直接用excel存么，感觉数据量并不大。然后搞个定时任务，将excel内容更新到CSV?

但 excel 是二进制文件，如果提交上来是很难 review 的，而且没法儿 diff

**Comment by zhoucheney** [comment]
感觉不太对，为什么这些信息直接在前端录入，然后给管理员审核，审核之后再存到csv里。增量的话都不需要看以前的，删除记录或者修改记录这种信息都可以存到csv里，审核也特别方便，逻辑也不复杂。

**Comment by 16647615268** [comment]
每个CSV表格的数据量不会很大，只是频繁更新数据和多方共同操作的问题，还是建议使用CSV格式进行存储，毕竟好多人并不常使用石墨表格。

**Comment by frank-zsy** [comment]
@zhoucheney 嗯，新的流程是这样的，@16647615268 根据昨天实践结果来看，GitHub 直接提交文本数据文件的门槛过高，冲突概率也大，石墨协作自动导入会大幅提升效率

**Comment by ydlover** [comment]
csv限制太多(例如字符串的空格，逗号等)，数据存储的话xml，json这些都比csv好

**Comment by thinkinnight** [comment]
现在这个是不是已经确定使用石墨文档？那就先关掉该issue了。
