### ISSUE TITLE
能否多个疫情地图

### ISSUE THREAD

**Issue by bebestmaple** [wuhan2020/wuhan2020#59]
能否多个疫情地图，详细到县区的，现在网上的大多是到省一级的

**Comment by frank-zsy** [comment]
非常有意义，但目前是否有可靠的数据源可以精确到县区级？

**Comment by aboutmydreams** [comment]
目前没有“可靠”的数据，只能更具网路传言做模型预测

**Comment by Charliecheung2** [comment]
确实没有可靠的数据这点难以实现，除非有第一信息源现身，就是身边的直系亲属或者朋友确诊/隔离，而非传闻那种，就是提高筛选门槛

**Comment by frank-zsy** [comment]
若可以提供有效可靠的数据源，请重启打开该 Issue

**Comment by mylesieong** [comment]
目前看到有丁香醫生這個,  https://3g.dxy.cn/newh5/view/pneumonia 稱据衛建委數据所制
