### ISSUE TITLE
[doc]有关Readme.md中石墨文档链接404的问题

### ISSUE THREAD

**Issue by shadowings-zy** [wuhan2020/wuhan2020#62]
您好，本项目中Readme.md中石墨文档的链接为空，请问这是怎么一回事呢？
<img width="369" alt="截屏2020-01-26上午10 45 23" src="https://user-images.githubusercontent.com/29225966/73129907-24980200-4029-11ea-8e0e-415b55b2dde1.png">

**Comment by frank-zsy** [comment]
目前正在构建文档中，尚未加入 README，稍后全部设置妥当后加入链接

**Comment by bhq01** [comment]
摊子铺太大了，下线服务的升级方式不太友好

**Comment by frank-zsy** [comment]
这是之前设计的失误，本来想完全通过 GitHub 程序员协作，但问题较多，所以修改了协作模式，项目到现在仅一天时间，之后前端会在其他项目中重新上线，这也是为了保证大家可以快速协同而做的改变。

**Comment by alienzj** [comment]
能否用google文档？

**Comment by frank-zsy** [comment]
> 能否用google文档？

Google 文档需要翻墙吧，这个门槛就太高了，我们希望任何人可以快速录入信息

**Comment by manyHaitao** [comment]
有没有定义需求文档？

**Comment by zhuangbiaowei** [comment]
问题已经解决，本issue关闭
