### ISSUE TITLE
新人如何迅速参与问题

### ISSUE THREAD

**Issue by xiataijie** [wuhan2020/wuhan2020#63]
能够提供一份详细参与的说明文档

**Comment by Charliecheung2** [comment]
看CONTRIBUTION.md

**Comment by Jingbinjie** [comment]
建议由熟悉GitHub的朋友来做信息传递，新手短时间可能有点困难。写代码的很多都会GitHub的，社科里需要使用R 或者Python的，也有玩得转的。 @xiataijie

**Comment by zhuangbiaowei** [comment]
本问题已经解决
