### ISSUE TITLE
注意信息安全，尤其是数据安全

### ISSUE THREAD

**Issue by minidoll** [wuhan2020/wuhan2020#65]
数据信息安全方面需要特别注意

**Comment by zhuangbiaowei** [comment]
@minidoll 请描述具体需要注意的内容，否则这个issue，没法响应。

**Comment by a0x** [comment]
![image](https://user-images.githubusercontent.com/3829546/73130440-59a95200-4033-11ea-9649-2ecd2e3be775.png)

**Comment by zhuangbiaowei** [comment]
如果，我们把一个原本就公开的信息，放在另一个公开的地方集中展示，并不能叫做泄露。

假设，我们把信息放在国内的某个网站或者，自己架设的某个网站。

国外的人一样能够看到。所以，只要是公开的信息，关键不在于放在那里，而是这些信息：是否遵循了：有限、必要的原则。

**Comment by frank-zsy** [comment]
是的，我们也已经在和专业律师沟通此事，收到明确答复后会注明在项目中。

但我们在文档中反复说明，我们是数据收集平台，而非数据发布平台，所有收集到该项目的数据必须已经在公网由官方渠道发布，不知道这样有没有问题？

**Comment by shengjk** [comment]
@minidoll , minidoll，你指的信息安全是否如 [建议](https://github.com/wuhan2020/wuhan2020/issues/38)中描述的那样

**Comment by JGX020** [comment]
我可以帮你们你们可以把数据加密放到数据库里，就算破解了库的密码也不一定破解加密数据
