### ISSUE TITLE
[BUG]README 链接失效

### ISSUE THREAD

**Issue by JiaxiangBU** [wuhan2020/wuhan2020#69]
`具体数据提交途径，请到[石墨文档]()` 这里的链接为空，

`具体数据信息请点击[这里](data/hospital.yml)` 这里的文件`data/hospital.yml`已经不再 master 了。

**Comment by JiaxiangBU** [comment]
https://github.com/wuhan2020/wuhan2020/issues/9#issuecomment-578445585 参考这个 comments，目前这个文件应该后续会上传？

**Comment by zhuangbiaowei** [comment]
问题已经解决，本issue关闭
