### ISSUE TITLE
[Feature]添加前端展示页面

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/wuhan2020#7]
添加各类信息的前端展示页面，提供信息的实时展示能力，需能够兼容移动端。

**Comment by LiuChangFreeman** [comment]
1、如果发布H5页面则需要一个不会被QQ、微信屏蔽的域名，以及防范被恶意举报
2、需要API服务器，微信小程序要求域名完成备案+https。如果使用serverless则可以使用云服务商提供的api gateway，但是有可能会被微信拦截。
3、需要开通静态资源CDN服务，在IOS下如果使用跨域cookie则很有可能会失效，因此前端静态资源跟API服务器需要使用同一个域名。

**Comment by LiuChangFreeman** [comment]
如果只考虑开发手机版，基于我们团队以往的技术方案，前端可以选择使用两种技术路线

1、H5网页:antd-mobile+dva+react
需要做以下准备:
1. 已备案的域名  
2. 发布前端网页用的CDN+OSS  

2、微信:weui+小程序基础框架
需要做以下准备:
1. 企业级开发者账号  
2. 微信支付  
3. 已备案的域名  
4. 一天的审核时间

**Comment by frank-zsy** [comment]
个人建议使用方案一，目前已备案域名及同域名 CDN 我都有，数据直接从 GitHub 仓库中获取，所以不一定需要 OSS，而且方案一技术栈 X-lab 团队比较驾轻就熟。
另外小程序申请春节期间暂停，初六恢复，还需要审核周期，可以考虑先用方案一开发，一期上线后开始准备小程序版本。
预计方案一的展示页面开发周期大约多久？

**Comment by sodabear** [comment]
我是后端开发(java)和数据分析(python), 不是很会前端, 我这边可以提供一些什么帮助吗？

**Comment by frank-zsy** [comment]
@sodabear 那是否可以做一些数据爬虫，从主要媒体渠道爬取实时信息，以 Issue 形式提交到该项目中？

**Comment by LiuChangFreeman** [comment]
> 个人建议使用方案一，目前已备案域名及同域名 CDN 我都有，数据直接从 GitHub 仓库中获取，所以不一定需要 OSS，而且方案一技术栈 X-lab 团队比较驾轻就熟。
> 另外小程序申请春节期间暂停，初六恢复，还需要审核周期，可以考虑先用方案一开发，一期上线后开始准备小程序版本。
> 预计方案一的展示页面开发周期大约多久？

几天内应该就行了，如果初期只是纯展示的话

**Comment by frank-zsy** [comment]
@LiuChangFreeman 那你来弄一下吧，有空吗？也可以搭个架子大家来写

**Comment by LiuChangFreeman** [comment]
> @LiuChangFreeman 那你来弄一下吧，有空吗？也可以搭个架子大家来写

代码仓库在哪搭建呢？就在本项目？

**Comment by frank-zsy** [comment]
我感觉新开一个项目比较好，这个项目仅用于信息收集吧，你觉得呢？

**Comment by LiuChangFreeman** [comment]
> 我感觉新开一个项目比较好，这个项目仅用于信息收集吧，你觉得呢？

好的，我去开一个前端项目，同时后端先用python搭一个纯作代理使用的api server
1.  前端预留好接口的设计
2. 每分钟缓存github仓库的csv
3. 提供restful接口给前端查询
4. 使用阿里云的serverless部署

**Comment by LiuChangFreeman** [comment]
https://github.com/LiuChangFreeman/wuhan2020-front

**Comment by frank-zsy** [comment]
@LiuChangFreeman OK，差不多以后可以直接在这个 org 下开一个项目，然后提交上来

**Comment by LiuChangFreeman** [comment]
> @LiuChangFreeman OK，差不多以后可以直接在这个 org 下开一个项目，然后提交上来

https://github.com/wuhan2020/front-pages

**Comment by xuexingdong** [comment]
@LiuChangFreeman 我可以做后端工作 技术站java+python 有什么可以分担的吗

**Comment by LiuChangFreeman** [comment]
> @LiuChangFreeman 我可以做后端工作 技术站java+python 有什么可以分担的吗

请到这里讨论:
https://github.com/wuhan2020/wuhan2020/issues/17

**Comment by zy9852** [comment]
可以帮忙前端页面的工作，有什么可以分担的么？

**Comment by TechHXJ** [comment]
请问有什么规划吗？有什么需求

**Comment by frank-zsy** [comment]
前端工作请移步前端项目，该项目由 @LiuChangFreeman 同学领头开发 @zy9852 @TechHXJ

**Comment by TechQuery** [comment]
已基于规范后的 CSV 开发了 PWA #34

**Comment by TechQuery** [comment]
Web 前端代码已全部移至 https://github.com/wuhan2020/wuhan2020.github.io
