### ISSUE TITLE
readme的石墨链接都写错了，都写成了github链接，而且还404

### ISSUE THREAD

**Issue by xirless** [wuhan2020/wuhan2020#73]

**Comment by heming6666** [comment]
README已更新。现在是好的了。

**Comment by liweierhuo** [comment]
还是打不开呀

**Comment by heming6666** [comment]
> ## 医院
> 具体数据提交途径，请到[石墨文档](https://shimo.im/sheets/k399pHyt6HKvW6xR/MODOC/)。
> 具体数据信息请点击[这里](data/hospital.yml)。

数据提交途径里的**石墨文档**链接可以打开。数据信息的链接，等后续从石墨文档把数据同步过来就可以打开了。 @liweierhuo @xirless

**Comment by A1meng** [comment]
没有编辑权限的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"heming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月26日(星期天) 中午1:45
收件人:&nbsp;"wuhan2020/wuhan2020"<wuhan2020@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wuhan2020/wuhan2020] readme的石墨链接都写错了，都写成了github链接，而且还404 (#73)



 
医院
 
具体数据提交途径，请到石墨文档。
 具体数据信息请点击这里。
  
数据提交途径里的石墨文档链接可以打开。数据信息的链接，等后续从石墨文档把数据同步过来就可以打开了。 @liweierhuo @xirless

**Comment by heming6666** [comment]
@A1meng 由于参与人员较多，不开放所有人员的编辑权限，请在[这里](https://shimo.im/forms/YVJkGrGCWwQPTpqY/fill)填写申请，会定向邀请到特定表单中进行信息录入。

#74

**Comment by A1meng** [comment]
恩 和刚刚那位说一声 @Qubot



由于参与人员较多，不开放所有人员的编辑权限，请在这里填写申请，会定向邀请到特定表单中进行信息录入。


具体数据提交途径，请到石墨文档。
具体数据信息请点击这里。

数据提交途径里的石墨文档链接可以打开。数据信息的链接，等后续从石墨文档把数据同步过来就可以打开了。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"heming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月26日(星期天) 中午1:48
收件人:&nbsp;"wuhan2020/wuhan2020"<wuhan2020@noreply.github.com&gt;;
抄送:&nbsp;"Terminal"<784108273@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wuhan2020/wuhan2020] readme的石墨链接都写错了，都写成了github链接，而且还404 (#73)




@A1meng 由于参与人员较多，不开放所有人员的编辑权限，请在这里填写申请，会定向邀请到特定表单中进行信息录入。
 
#74

**Comment by leinue** [comment]
提 issues 的时候请耐心点哦。
Please be patient when submiting new issues, Your tone is not right.

**Comment by JiaxiangBU** [comment]
嗯这个问题，我提交过了，无效链接的问题。

**Comment by zhuangbiaowei** [comment]
问题已经解决，本issue关闭
