### ISSUE TITLE
无法编辑石墨文档，无权限。

### ISSUE THREAD

**Issue by SevenTailCat** [wuhan2020/wuhan2020#74]

**Comment by heming6666** [comment]
由于参与人员较多，不开放所有人员的编辑权限，请在[这里](https://shimo.im/forms/YVJkGrGCWwQPTpqY/fill)填写申请，会定向邀请到特定表单中进行信息录入。

**Comment by zhuangbiaowei** [comment]
本问题已经解决，信息已经更新到贡献者指南了。

https://github.com/wuhan2020/wuhan2020/blob/master/CONTRIBUTION.md
