### ISSUE TITLE
可以写前端，数据API哪里有？

### ISSUE THREAD

**Issue by hsowan-me** [wuhan2020/wuhan2020#77]

**Comment by skydownacai** [comment]
朋友加个微信，我们做个可视化平台出来

**Comment by 501697405** [comment]
有API 了吗

**Comment by hsowan-me** [comment]
你做服务端吗，我的微信wan1583096683

**Comment by skydownacai** [comment]
数据只能做爬虫。目前只是把丁香医生的数据抓出来了。我觉得我们至少可以做到每个市的人数可视化。

> 
> 
> 你做服务端吗，我的微信wan1583096683

**Comment by hsowan-me** [comment]
![image](https://user-images.githubusercontent.com/55872984/73132269-c6ccdf80-4053-11ea-8925-f6feec5a3b35.png)

**Comment by tongshuangwu** [comment]
各位：
为了避免信息分散，请各位[先加slack群吧](https://join.slack.com/t/wuhan2020/shared_invite/enQtOTIzNjA2MDYwOTUxLWVjMjA4MjdhNGVmZmZlZTgxYjM1ZDY1NGVkZDVkNGI0NzhjZGVlYTM2Mjc5Mjk2YjgyYTk1NDJmNTkxODZlOTE)
里面已建立前端、后端、数据同步等对应 channel，希望大家一起讨论，可以更好地把可视化融入到他们的frontpage里面

**Comment by norratek** [comment]
http://ncov.nosensor.com:8080/api/  
这个是我个人做的一个接口，可以获取每天的省/市的确诊人数

**Comment by pensacola1989** [comment]
> http://ncov.nosensor.com:8080/api/
> 这个是我个人做的一个接口，可以获取每天的省/市的确诊人数

数据来源？

**Comment by nwljy** [comment]
数据来源 网易
http://news.163.com/special/epidemic/?spssid=7dc3ace025c1193fdf6a842ea671d83d&spsw=1&spss=other#map_block
获取xpath地址：
省：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@class='hasCities']//div[@class='province']
市：/html/body/div[3]/div[2]/div[2]/ul[1]//li[@class='hasCities']//ul//li
已经用java验证过了

**Comment by inkydragon** [comment]
两个可以参考的人员流动数据

- [新型冠状病毒通过交通流的传播数据推演（含公开数据集与直播预告）](https://mp.weixin.qq.com/s/MHmFzvOBrZCTJoMTvMznSg)
- [武汉迁徙详情——百度地图慧眼](https://qianxi.baidu.com/)
