### ISSUE TITLE
武汉加油！！！加群vx: jess_andoid 

### ISSUE THREAD

**Issue by wenfu92** [wuhan2020/wuhan2020#79]

**Comment by will-ww** [comment]
> This issue has not been replied for 24 hours, please pay attention to this issue: @frank-zsy @zhangliqing @JerryKuan @sunshinemingo @bifenglin

是否可以把表伟加到这个提醒列表中来，他是issue终结者~ :-)  @frank-zsy

**Comment by zhuangbiaowei** [comment]
关闭此广告issue
