### ISSUE TITLE
【功能建议】建议实现感染病例实时监控可视化，并且同有关部门对接，实现一键上报功能。

### ISSUE THREAD

**Issue by mokeeqian** [wuhan2020/wuhan2020#81]
# 功能建议
丁香园的病情监控只是精确到了10分位，不够精确，建议通过爬虫等技术手段实时获取感染者信息（隐私信息脱敏），后台实时反馈给有关部门。
# 如何协作
目前哪些模块需要完成？

**Comment by Flyinet** [comment]
可以参考我之前的[issue](https://github.com/wuhan2020/wuhan2020/issues/78)，如果有建议comment一下方便前端开发者参考

**Comment by mokeeqian** [comment]
@Flyinet  好的，多谢！

**Comment by thinkinnight** [comment]
@mokeeqian 能问一下为什么reopen了这个issue吗？
