### ISSUE TITLE
我建议你们关闭！！

### ISSUE THREAD

**Issue by kitche1985** [wuhan2020/wuhan2020#83]
在现在消息难辨真伪的情况下这种非官方渠道的东西最后不要做！！！另外github不是让你们来做这个的。issue中有人说对接官方数据做下统计图之类的还差不多，这些私人性质的什么文档请最好不要做。

**Comment by bobyuxinyang** [comment]
信息真实性和有效性必须完善，并得到官方认可

**Comment by zhuangbiaowei** [comment]
本issue关闭，请参考FAQ：

https://github.com/wuhan2020/wuhan2020/blob/master/FAQ.md
