### ISSUE TITLE
别把github搞得这么不专业

### ISSUE THREAD

**Issue by kitche1985** [wuhan2020/wuhan2020#87]
知道大家是好心，但是请专业点，这里本来是和软件技术相关的网站，请不要用来做这个，另外对圈外人也并没有什么帮助，除非你们能对接官方渠道去做点什么信息发布，就算石墨文档权限管理严格，请问谁来保证信息本身不出问题，谁来核实真假，不要代替官方去做这些事情，尽管可能有不信任的因素在里面，但是这种事情上开源社区就更值得信任吗？本身就是开源社区你说交流技术无可厚非，此类还是不要的好

**Comment by Clifnich** [comment]
政府的技术能力有限，民间能提供帮助是一件好事。但我同意你对数据源真实性的质疑，所以这个项目在选择对外发布的信息方面一定要非常谨慎，千万别帮倒忙。

**Comment by zwOvO** [comment]
公益性质的可靠信息聚合平台，我觉得没问题呀。

**Comment by zwOvO** [comment]
我们不生产消息，我们只是可靠消息的搬运工

**Comment by zwOvO** [comment]
我们不生产信息，我们只是可靠信息的搬运工

**Comment by zhuangbiaowei** [comment]
本issue关闭，请参考FAQ：

https://github.com/wuhan2020/wuhan2020/blob/master/FAQ.md
