### ISSUE TITLE
其他平台已汇总的石墨文档，我们现在做的事情是否为另造轮子？

### ISSUE THREAD

**Issue by kelzr** [wuhan2020/wuhan2020#88]
https://shimo.im/docs/8hQKWGRR9RWqcwpY?from=timeline

**Comment by frank-zsy** [comment]
确实有很多收集信息的志愿者，但第一，大部分收集的信息没有可靠证实的来源，第二，都在石墨文档，没有自动化链条。

我们的所有信息需要人工审核，带有官方来源链接，并且最终是完全自动化的，大家在石墨中协同，我们会有志愿者审核，最终会自动到网站中展示、检索，也可供分析。而且由于石墨团队官方支持，我们的石墨文档是企业版全功能的，不限协作人数，并且有严格的审核权限控制，保证信息有效性。

**Comment by MiratPH** [comment]
建议项目首页添加更鲜明简短的项目目的描述，该项目类似OSINT概念，是对已发布权威信息对牵线搭桥
