### ISSUE TITLE
石墨文档没有编辑权限？

### ISSUE THREAD

**Issue by free2001-2020** [wuhan2020/wuhan2020#90]
我想提交一份医院数据，但是医院的石墨文档无编辑权限。请问该如何操作

**Comment by Guguant** [comment]
https://github.com/wuhan2020/wuhan2020#%E6%95%B0%E6%8D%AE%E5%88%86%E7%B1%BB

**Comment by Guguant** [comment]
> 我想提交一份医院数据，但是医院的石墨文档无编辑权限。请问该如何操作

https://github.com/wuhan2020/wuhan2020#数据分类

**Comment by zhuangbiaowei** [comment]
本问题已经解决，信息已经更新到贡献者指南了。
https://github.com/wuhan2020/wuhan2020/blob/master/CONTRIBUTION.md

**Comment by zhuangbiaowei** [comment]
本问题已经解决，信息已经更新到贡献者指南了。
https://github.com/wuhan2020/wuhan2020/blob/master/CONTRIBUTION.md
