### ISSUE TITLE
请求收集zf公布的发热病患的车次信息

### ISSUE THREAD

**Issue by KarlFreecss** [wuhan2020/wuhan2020#91]
各地方政府会公布本地发热人员所乘坐的次车，但是信息十分凌乱，而且一般只关注了本地的下站的人员，能否按照日期-车次的方式收集政府公布的乘车信息，方便大家查询。例如：
1月24日，武汉汉口出发（梅州西下），D3286
1月25日，武汉武昌出发（郑州下），K458
1月25日，郑州出发（齐齐哈尔南下），G1264
1月25日，齐齐哈尔南出发（达牙克市下），K995

**Comment by keeStep** [comment]
对于已确诊的乘客，最好能收集到其候车时间段及候车停留位置等。候车期间有没戴口罩，没戴的话有没去过洗手间，热水间，在这期间周围人群密度大概多少，有没打喷嚏，打喷嚏有无防护措施……

**Comment by zwOvO** [comment]
这些数据估计不好收集，需要有关部门介入，你懂得

**Comment by keeStep** [comment]
嗯，不可抗因素，我们就把发热病患的车次信息做个统计出来，因为，无论是空间上还是时间上还是平台等唯独，都比较分散。统计下方便查询

**Comment by WHOCARE2333** [comment]
可合并 https://github.com/wuhan2020/wuhan2020/issues/126

**Comment by KarlFreecss** [comment]
将这些合并到#126中去吧，他是专业做产品的，我相信他会做的更好。
