### ISSUE TITLE
[Doc] FAQ常见问题和答案收集

### ISSUE THREAD

**Issue by PengKuang** [wuhan2020/wuhan2020#97]
请把大家常问的问题及对应答案（如果知道的话）汇集到这里，我会添加一个FAQ.md文档到仓库里，帮助减少重复问题，提升协作效率。

**Comment by PengKuang** [comment]
Q: 目前Slack上的channel有哪些？
A: 除了默认的general频道，还有:

问题及建议提交频道（Github机器人自动监测更新）：
#anti-2019-ncov 

前端web页面开发频道：
#front-pages

数据可视化频道：
#map-visualization

API设计开发频道（Python）：
#api-server

数据同步频道（TS）：
#data-sync

数据录入相关频道：
医院 #data-hospital 
酒店 #data-hotel
物流 #data-logistical
生产 #data-factory
捐赠 #data-donation
义诊 #data-clinic

**Comment by frank-zsy** [comment]
赞，可以整理成 md 文档提交 PR
